# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'gofeedback' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for gofeedback
  pod 'SideMenu'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'Alamofire', '~> 4.7'
  pod 'Firebase', '>= 2.5.0'
  pod 'FirebaseStorage'
  pod 'FirebaseAuth'
  pod 'Cosmos', '~> 21.0'
  pod 'SnapKit'
  
  # add pods for desired Firebase products
  # https://firebase.google.com/docs/ios/setup#available-pods
  
  target 'gofeedbackTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
