# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
def available_pods

  # Pods for gofeedback
  pod 'SideMenu'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'Firebase', '>= 2.5.0'
  pod 'FirebaseStorage'
  pod 'FirebaseAuth'
  pod 'Cosmos', '~> 21.0'
  pod 'SnapKit'
  pod 'Firebase/Firestore'
  pod 'FirebaseFirestoreSwift'
  pod 'OpalImagePicker'
  pod 'AlamofireObjectMapper', '~> 5.2'
  pod 'Alamofire', '~> 4.7'
  pod 'ObjectMapper', '~> 3.5'
  pod 'CDYelpFusionKit'
  pod 'YPImagePicker'
  pod 'UBottomSheet'

  # add pods for desired Firebase products
  # https://firebase.google.com/docs/ios/setup#available-pods
 end

  target 'gofeedback' do
   available_pods
  end
  
  target 'gofeedbackadmin' do
    available_pods
  end

  target 'gofeedbackTests' do
    inherit! :search_paths
    # Pods for testing
  end
